from crawler import Patent
from typing import List, Tuple

def get_patents(self, date_from, date_to = ..., ipc = ..., limit = 50) -> Tuple[int, List[Patent]]: ...
def add_patents(self, patents): ...
def get_users(self) -> Tuple[str, List[str]]: ...
def add_users(self, users): ...